name: game_testing
description: Project to test game plugins and approaches

publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  flame:
    path: ../flame/packages/flame/
  flame_forge2d:
    path: ../flame/packages/flame_forge2d/

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
